version: '3.8'

services:
  frontend:
    container_name: bconic_frontend_container
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_BASE_URL=http://localhost:5000/api/v1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - FAST_REFRESH=true
    stdin_open: true
    tty: true
    depends_on:
      - backend