name: BConic Frontend CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clean Workspace
      - name: Clean workspace
        run: |
          echo "========Executing Clean Workspace========"
          rm -rf *

      # Checkout SCM
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: main
        
      # Verify Tools
      - name: Verify tools
        run: |
          echo "========Verify Tools========"
          node --version
          npm --version
          git --version

      # Verify Branch
      - name: Verify branch
        run: |
          git branch -a
          git log -1 --oneline

      # Install Dependencies
      - name: Install dependencies
        run: npm ci

      # Unit Testing
      - name: Run unit tests
        run: npm test
      
      # Build Project
      - name: Build project
        run: |
          npm install --save-dev @babel/plugin-proposal-private-property-in-object
          npx update-browserslist-db@latest
          npm run build